// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDitXv55lkt6CImrEeXO3Ur4_CIc4wmcQg',
    appId: '1:119754616813:web:b460640991377a7478c1e4',
    messagingSenderId: '119754616813',
    projectId: 'fooddiary-36224',
    authDomain: 'fooddiary-36224.firebaseapp.com',
    storageBucket: 'fooddiary-36224.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMstSqo8918S_YuF6sZad72bza_8lv4hQ',
    appId: '1:119754616813:android:feca4889271fa46f78c1e4',
    messagingSenderId: '119754616813',
    projectId: 'fooddiary-36224',
    storageBucket: 'fooddiary-36224.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnmw8zupBPwkTSa5ekiNXJOzjQmDTbobI',
    appId: '1:119754616813:ios:117dade97405222778c1e4',
    messagingSenderId: '119754616813',
    projectId: 'fooddiary-36224',
    storageBucket: 'fooddiary-36224.firebasestorage.app',
    iosBundleId: 'com.example.foodDiaryRecipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnmw8zupBPwkTSa5ekiNXJOzjQmDTbobI',
    appId: '1:119754616813:ios:117dade97405222778c1e4',
    messagingSenderId: '119754616813',
    projectId: 'fooddiary-36224',
    storageBucket: 'fooddiary-36224.firebasestorage.app',
    iosBundleId: 'com.example.foodDiaryRecipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDitXv55lkt6CImrEeXO3Ur4_CIc4wmcQg',
    appId: '1:119754616813:web:d9abf6d793f6860478c1e4',
    messagingSenderId: '119754616813',
    projectId: 'fooddiary-36224',
    authDomain: 'fooddiary-36224.firebaseapp.com',
    storageBucket: 'fooddiary-36224.firebasestorage.app',
  );

}